import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { IngestedFacts } from "@/lib/documentParser";

export interface ExportableCaseDocument {
  id: string;
  filename: string;
  document_type: string | null;
  summary: string | null;
  facts: IngestedFacts;
  simulation_inputs: IngestedFacts["simulationInputs"] | null;
  ocr_used: boolean;
  file_size_kb: number | null;
  created_at: string;
}

const NAVY: [number, number, number] = [15, 23, 42];
const SILVER: [number, number, number] = [148, 163, 184];
const ACCENT: [number, number, number] = [99, 132, 255];
const RED: [number, number, number] = [220, 70, 70];

export type PageScale = "a4" | "letter" | "legal" | "a3";

export interface ExportSettings {
  title?: string;
  pageScale?: PageScale;
  includeOcrNotes?: boolean;
  includeRedFlags?: boolean;
  redactRedFlags?: boolean;
}

export function exportCaseLibraryPDF(docs: ExportableCaseDocument[], opts?: ExportSettings) {
  if (!docs.length) return;

  const pageScale: PageScale = opts?.pageScale || "a4";
  const includeOcrNotes = opts?.includeOcrNotes ?? true;
  const includeRedFlags = opts?.includeRedFlags ?? true;
  const redactRedFlags = opts?.redactRedFlags ?? false;

  const pdf = new jsPDF({ unit: "pt", format: pageScale });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 40;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin) {
      pdf.addPage();
      y = margin;
    }
  };

  const heading = (text: string, size = 18, color = NAVY) => {
    ensureSpace(size + 10);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    pdf.text(text, margin, y);
    y += size + 6;
  };

  const sub = (text: string, size = 11, color: [number, number, number] = SILVER) => {
    ensureSpace(size + 4);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    pdf.text(text, margin, y);
    y += size + 4;
  };

  const para = (text: string, size = 10) => {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(size);
    pdf.setTextColor(40, 40, 40);
    const lines = pdf.splitTextToSize(text, pageW - margin * 2);
    lines.forEach((ln: string) => {
      ensureSpace(size + 2);
      pdf.text(ln, margin, y);
      y += size + 2;
    });
  };

  const divider = () => {
    ensureSpace(10);
    pdf.setDrawColor(...SILVER);
    pdf.setLineWidth(0.5);
    pdf.line(margin, y, pageW - margin, y);
    y += 10;
  };

  // ---- Cover ----
  pdf.setFillColor(...NAVY);
  pdf.rect(0, 0, pageW, 110, "F");
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(26);
  pdf.setTextColor(255, 255, 255);
  pdf.text("ProLAW Case Library Report", margin, 60);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(...SILVER);
  pdf.text(opts?.title || "Confidential — Generated by ProLAW Agentic Legal Intelligence", margin, 82);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, 98);

  y = 140;
  heading(`Library Overview (${docs.length} document${docs.length === 1 ? "" : "s"})`, 14, NAVY);
  const overviewHead = ["#", "Filename", "Type", "Parties"];
  if (includeRedFlags) overviewHead.push("Red Flags");
  if (includeOcrNotes) overviewHead.push("OCR");
  overviewHead.push("Date");

  autoTable(pdf, {
    startY: y,
    head: [overviewHead],
    body: docs.map((d, i) => {
      const row: string[] = [
        String(i + 1),
        d.filename,
        d.document_type || "—",
        String(d.facts?.parties?.length || 0),
      ];
      if (includeRedFlags) row.push(String(d.facts?.redFlags?.length || 0));
      if (includeOcrNotes) row.push(d.ocr_used ? "Yes" : "No");
      row.push(new Date(d.created_at).toLocaleDateString());
      return row;
    }),
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: NAVY, textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 252] },
    margin: { left: margin, right: margin },
  });
  y = (pdf as any).lastAutoTable.finalY + 20;

  // ---- Per-document detail ----
  docs.forEach((d, idx) => {
    pdf.addPage();
    y = margin;

    heading(`${idx + 1}. ${d.filename}`, 16, NAVY);
    sub(`${d.document_type || "Document"} • ${d.file_size_kb ?? "?"} KB • Saved ${new Date(d.created_at).toLocaleString()}`);
    if (d.ocr_used && includeOcrNotes) {
      pdf.setFillColor(...ACCENT);
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      const tag = "OCR APPLIED";
      const tw = pdf.getTextWidth(tag) + 10;
      pdf.roundedRect(margin, y, tw, 14, 3, 3, "F");
      pdf.text(tag, margin + 5, y + 10);
      y += 22;
    }

    // Bilingual / multilingual badge + breakdown
    const bilingual = (d.facts as any)?.bilingual as
      | { scripts: string[]; segments: number; blocks?: { label: string; charCount: number }[] }
      | null
      | undefined;
    if (includeOcrNotes && bilingual && (bilingual.scripts?.length || bilingual.segments)) {
      pdf.setFillColor(120, 80, 200);
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      const btag = `MULTILINGUAL · ${bilingual.scripts?.length ?? "?"} SCRIPTS`;
      const btw = pdf.getTextWidth(btag) + 10;
      pdf.roundedRect(margin, y, btw, 14, 3, 3, "F");
      pdf.text(btag, margin + 5, y + 10);
      y += 22;

      heading("Bilingual Script Segmentation", 12);
      para(
        `This document was automatically split into ${bilingual.segments} script block${bilingual.segments === 1 ? "" : "s"} ` +
        `covering: ${(bilingual.scripts || []).join(", ")}. Each block was extracted independently to maximize accuracy ` +
        `across mixed-script content (e.g. translated contracts, bilingual filings).`
      );
      if (bilingual.blocks?.length) {
        autoTable(pdf, {
          startY: y,
          head: [["#", "Script", "Characters"]],
          body: bilingual.blocks.map((b, i) => [String(i + 1), b.label, String(b.charCount)]),
          styles: { fontSize: 9, cellPadding: 4 },
          headStyles: { fillColor: [120, 80, 200], textColor: 255 },
          margin: { left: margin, right: margin },
        });
        y = (pdf as any).lastAutoTable.finalY + 12;
      } else {
        y += 4;
      }
    }

    divider();

    if (d.summary) {
      heading("Summary", 12);
      para(d.summary);
      y += 4;
    }

    // Parties
    if (d.facts?.parties?.length) {
      heading("Parties", 12);
      autoTable(pdf, {
        startY: y,
        head: [["Name", "Role"]],
        body: d.facts.parties.map(p => [p.name, p.role]),
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255 },
        margin: { left: margin, right: margin },
      });
      y = (pdf as any).lastAutoTable.finalY + 12;
    }

    // Key dates
    if (d.facts?.keyDates?.length) {
      heading("Key Dates", 12);
      autoTable(pdf, {
        startY: y,
        head: [["Date", "Event"]],
        body: d.facts.keyDates.map(k => [k.date, k.event]),
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255 },
        margin: { left: margin, right: margin },
      });
      y = (pdf as any).lastAutoTable.finalY + 12;
    }

    // Monetary amounts
    if (d.facts?.monetaryAmounts?.length) {
      heading("Monetary Amounts", 12);
      autoTable(pdf, {
        startY: y,
        head: [["Amount", "Context"]],
        body: d.facts.monetaryAmounts.map(m => [m.amount, m.context]),
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255 },
        margin: { left: margin, right: margin },
      });
      y = (pdf as any).lastAutoTable.finalY + 12;
    }

    // Legal issues / citations
    if (d.facts?.legalIssues?.length) {
      heading("Legal Issues & Citations", 12);
      d.facts.legalIssues.forEach(li => para(`• ${li}`));
      y += 4;
    }

    // Key clauses with risk
    if (d.facts?.keyClauses?.length) {
      heading("Clause Risk Analysis", 12);
      autoTable(pdf, {
        startY: y,
        head: [["Risk", "Clause", "Note"]],
        body: d.facts.keyClauses.map(c => [c.risk.toUpperCase(), c.clause, c.note]),
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: NAVY, textColor: 255 },
        columnStyles: { 0: { cellWidth: 50 } },
        didParseCell: (data) => {
          if (data.section === "body" && data.column.index === 0) {
            const v = String(data.cell.raw).toLowerCase();
            if (v === "high") data.cell.styles.textColor = RED;
            else if (v === "medium") data.cell.styles.textColor = [200, 140, 0];
            else data.cell.styles.textColor = [0, 130, 80];
            data.cell.styles.fontStyle = "bold";
          }
        },
        margin: { left: margin, right: margin },
      });
      y = (pdf as any).lastAutoTable.finalY + 12;
    }

    // Evidence
    if (d.facts?.evidenceItems?.length) {
      heading("Evidence Items", 12);
      d.facts.evidenceItems.forEach(e => para(`• ${e}`));
      y += 4;
    }

    // Red flags (sensitive — controlled by export settings)
    if (includeRedFlags && d.facts?.redFlags?.length) {
      heading("Red Flags", 12, RED);
      d.facts.redFlags.forEach(r => {
        if (redactRedFlags) {
          // Redact: keep first word, mask the rest
          const words = r.split(/\s+/);
          const masked = words.map((w, i) => i === 0 ? w : "█".repeat(Math.min(w.length, 8))).join(" ");
          para(`⚠ ${masked}  [REDACTED]`);
        } else {
          para(`⚠ ${r}`);
        }
      });
      y += 4;
    } else if (!includeRedFlags && d.facts?.redFlags?.length) {
      heading("Red Flags", 12, SILVER);
      para(`${d.facts.redFlags.length} sensitive red-flag item(s) excluded from this export per export settings.`);
      y += 4;
    }

    // Simulation inputs
    const sim = d.simulation_inputs || d.facts?.simulationInputs;
    if (sim) {
      heading("Simulation Inputs", 12);
      autoTable(pdf, {
        startY: y,
        head: [["Parameter", "Value"]],
        body: [
          ["Evidence Strength", `${sim.evidenceStrength}/100`],
          ["Witness Credibility", `${sim.witnessCredibility}/100`],
          ["Documentation Quality", `${sim.documentationQuality}/100`],
          ["Opposition Strength", `${sim.oppositionStrength}/100`],
          ["Timeline Urgency", `${sim.timelineUrgency}/100`],
          ["Public Sentiment", `${sim.publicSentiment}/100`],
          ["Suggested Venue", sim.suggestedVenue],
          ["Suggested Strategy", sim.suggestedStrategy],
        ],
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255 },
        margin: { left: margin, right: margin },
      });
      y = (pdf as any).lastAutoTable.finalY + 8;
      if (sim.rationale) {
        sub("Rationale", 10, NAVY);
        para(sim.rationale);
      }
    }

    // OCR / processing notes (optional)
    if (includeOcrNotes) {
      heading("Processing Notes", 12);
      para(`OCR was ${d.ocr_used ? "applied to one or more scanned pages or images" : "not required (digital text was readable)"}. Extraction performed by ProLAW Document Intelligence.`);
    }

    if (d.facts?.recommendedQuestions?.length) {
      heading("Recommended Follow-up Questions", 12);
      d.facts.recommendedQuestions.forEach(q => para(`? ${q}`));
    }
  });

  // Footer page numbers
  const total = pdf.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    pdf.setPage(i);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...SILVER);
    pdf.text(`ProLAW Case Library  •  Page ${i} of ${total}`, pageW / 2, pageH - 18, { align: "center" });
  }

  const fname = `prolaw-case-library-${new Date().toISOString().slice(0, 10)}.pdf`;
  pdf.save(fname);
}
